basePath: /api/v1
definitions:
  controllers.Comment:
    properties:
      message:
        type: string
      time:
        type: string
      user:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple comment system API
  title: Simple Comment System API
  version: "1.0"
paths:
  /comments:
    get:
      description: Get all comments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Comment'
            type: array
      summary: Get Comments
    post:
      consumes:
      - application/json
      description: Post a new comment
      parameters:
      - description: Comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/controllers.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Post Comment
  /login:
    post:
      consumes:
      - application/json
      description: Login to the system
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Login
swagger: "2.0"
